### ISSUE TITLE
Implement email generator

### ISSUE THREAD

**Issue by Krish-Bhalala** [Krish-Bhalala/Acadmeic-Learning-Centre-Admin-Scripts#2]
emailDataGenerator(reciever, subject, sender)

generates the basic structure of an email in the form of array
return [Reciever email id, subject, current date, current week (eg- Monday Dec 2, 2024 to Sunday Dec 8, 2024), salutary remarks + contact info of sender]

**Comment by Fahad-Ali-Khan-ca** [comment]
Hi, I would like to work on this issue,

**Comment by Krish-Bhalala** [comment]
sure feel free to fork and create a pull request, I'll review it. Make sure to follow the guidelines and appropriate standards
