### ISSUE TITLE
Implement Email Sending Feature

### ISSUE THREAD

**Issue by Krish-Bhalala** [Krish-Bhalala/Acadmeic-Learning-Centre-Admin-Scripts#3]
sendEmail(list emailData, recieverEmail)

send an email with emailData to <recieverEmail> using any library.
assume emailData follows following pattern : [reciever email, subject, body, email closing, senders email]
return true if email is successfully sent 
else return "email not sent"

**Comment by Fahad-Ali-Khan-ca** [comment]
Hi, I would like to work on this issue
